name: Run E2E Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run the tests for
permissions:
  id-token: write
  contents: write
jobs:
  run-e2e-tests:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/${{ inputs.environment }}-run-e2e-tests-role
          aws-region: eu-west-2
          role-session-name: RunTests
      - run: |
          pip install boto3
          python ./.github/scripts/run_ecs_task.py ${{ inputs.environment }}
      - name: Send failure message
        uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: E2E tests have failed. <https://github.com/nationalarchives/dr2-e2e-tests/actions/runs/${{ github.run_id }}|View the workflow run>"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
